export enum ServiceMode {
  INDO = "INDO",
  BATAK = "BATAK",
}

export enum SongSource {
  BE = "BE",
  BN = "BN",
  KJ = "KJ",
  PKJ = "PKJ",
  NKB = "NKB",
}

export const SERVICE_INFO = {
  [ServiceMode.INDO]: {
    label: "Indonesia",
    alkitabDb: "/db/alkitab/indo/",
    patikFormat: "Hukum Taurat\\ ?:?\\ ?(.+)",
    epistelFormat: "Epistel\\ ?:?\\ ?(.+)",
    jamitaFormat: "Khotbah\\ ?:?\\ ?(.+)",
    standFormat: "ayat([0-9]+)berdiri",
    static: {
      votum: "Votum – Introitus – Doa",
      patik: "Hukum Taurat",
      dosa: "Pengakuan Dosa",
      epistel: "Epistel",
      iman: "Pengakuan Iman Rasuli",
      warta: "Warta Jemaat",
      jamita: "Khotbah",
      doa: "Doa Persembahan – Berkat",
    },
  },
  [ServiceMode.BATAK]: {
    label: "Batak",
    alkitabDb: "/db/alkitab/batak/",
    patikFormat: "Patik\\ ?:?\\ ?(.+)",
    epistelFormat: "Epistel\\ ?:?\\ ?(.+)",
    jamitaFormat: "Khotbah\\ ?:?\\ ?(.+)",
    standFormat: "ayat([0-9]+)jongjong",
    static: {
      votum: "Votum – Introitus – Tangiang",
      patik: "Patik",
      dosa: "Manopoti Dosa",
      epistel: "Epistel",
      iman: "Manghatindanghon Haporseaon",
      warta: "Tingting Huria",
      jamita: "Khotbah",
      doa: "Tangiang Pelean – Pasupasu",
    },
  },
};

export const SONG_INFO = {
  [SongSource.BE]: {
    songDb: "/db/BE.json",
    author: "Buku Ende",
    music: "Musik",
    stand: "Jongjong",
  },
  [SongSource.BN]: {
    songDb: "/db/BN.json",
    author: "Buku Nyanyian HKBP",
    music: "Musik",
    stand: "Berdiri",
  },
  [SongSource.KJ]: {
    songDb: "/db/KJ.json",
    author: "Kidung Jemaat",
    music: "Musik",
    stand: "Berdiri",
  },
  [SongSource.PKJ]: {
    songDb: "/db/PKJ.json",
    author: "Pelengkap Kidung Jemaat",
    music: "Musik",
    stand: "Berdiri",
  },
  [SongSource.NKB]: {
    songDb: "/db/NKB.json",
    author: "Nyanyian Kidung Baru",
    music: "Musik",
    stand: "Berdiri",
  },
};

export enum TEMPLATE_KEY {
  SONG_XML = "song_xml",
}

export const ALKITAB_INFO: Record<ServiceMode, string[]> = {
  [ServiceMode.INDO]: [
    "Kejadian",
    "Keluaran",
    "Imamat",
    "Bilangan",
    "Ulangan",
    "Yosua",
    "Hakim-hakim",
    "Rut",
    "1 Samuel",
    "2 Samuel",
    "1 Raja-raja",
    "2 Raja-raja",
    "1 Tawarikh",
    "2 Tawarikh",
    "Ezra",
    "Nehemia",
    "Ester",
    "Ayub",
    "Mazmur",
    "Amsal",
    "Pengkhotbah",
    "Kidung Agung",
    "Yesaya",
    "Yeremia",
    "Ratapan",
    "Yehezkiel",
    "Daniel",
    "Hosea",
    "Yoel",
    "Amos",
    "Obaja",
    "Yunus",
    "Mikha",
    "Nahum",
    "Habakuk",
    "Zefanya",
    "Hagai",
    "Zakharia",
    "Maleakhi",
    "Matius",
    "Markus",
    "Lukas",
    "Yohanes",
    "Kisah Para Rasul",
    "Roma",
    "1 Korintus",
    "2 Korintus",
    "Galatia",
    "Efesus",
    "Filipi",
    "Kolose",
    "1 Tesalonika",
    "2 Tesalonika",
    "1 Timotius",
    "2 Timotius",
    "Titus",
    "Filemon",
    "Ibrani",
    "Yakobus",
    "1 Petrus",
    "2 Petrus",
    "1 Yohanes",
    "2 Yohanes",
    "3 Yohanes",
    "Yudas",
    "Wahyu",
  ],
  [ServiceMode.BATAK]: [
    "1 Musa",
    "2 Musa",
    "3 Musa",
    "4 Musa",
    "5 Musa",
    "Josua",
    "Panguhum",
    "Rut",
    "1 Samuel",
    "2 Samuel",
    "1 Raja-raja",
    "2 Raja-raja",
    "1 Kronika",
    "2 Kronika",
    "Esra",
    "Nehemia",
    "Ester",
    "Job",
    "Psalmen",
    "Poda",
    "Parjamita",
    "Angka Ende",
    "Jesaya",
    "Jeremia",
    "Andung-andung",
    "Hesekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obaja",
    "Jona",
    "Mika",
    "Nahum",
    "Habakuk",
    "Sepania",
    "Haggai",
    "Sakaria",
    "Maleaki",
    "Mateus",
    "Markus",
    "Lukas",
    "Johannes",
    "Ulaon ni Apostel",
    "Rom",
    "1 Korint",
    "2 Korint",
    "Galatia",
    "Epesus",
    "Pilippi",
    "Kolosse",
    "1 Tessalonik",
    "2 Tessalonik",
    "1 Timoteus",
    "2 Timoteus",
    "Titus",
    "Pilemon",
    "Heber",
    "Jakobus",
    "1 Petrus",
    "2 Petrus",
    "1 Johannes",
    "2 Johannes",
    "3 Johannes",
    "Judas",
    "Pangungkapon",
  ],
};
