export enum ServiceMode {
  INDO = "BN",
  BATAK = "BE",
}

export const SERVICE_INFO = {
  [ServiceMode.INDO]: {
    author: "Buku Nyanyian HKBP",
    stand: "Berdiri",
    music: "Musik",
    songDb: "/db/BN.json",
    alkitabDb: "/db/alkitab/indo/",
    patikFormat: "Hukum Taurat\\ ?:?\\ ?(.+)",
    epistelFormat: "Epistel\\ ?:?\\ ?(.+)",
    jamitaFormat: "Khotbah\\ ?:?\\ ?(.+)",
    standFormat: "ayat([0-9]+)berdiri",
    static: {
      votum: "Votum – Introitus – Doa",
      patik: "Hukum Taurat",
      dosa: "Pengakuan Dosa",
      epistel: "Epistel",
      iman: "Pengakuan Iman Rasuli",
      warta: "Warta Jemaat",
      jamita: "Khotbah",
      doa: "Doa Persembahan – Berkat",
    },
  },
  [ServiceMode.BATAK]: {
    author: "Buku Ende",
    stand: "Jongjong",
    music: "Musik",
    songDb: "/db/BE.json",
    alkitabDb: "/db/alkitab/batak/",
    patikFormat: "Patik\\ ?:?\\ ?(.+)",
    epistelFormat: "Epistel\\ ?:?\\ ?(.+)",
    jamitaFormat: "Khotbah\\ ?:?\\ ?(.+)",
    standFormat: "ayat([0-9]+)jongjong",
    static: {
      votum: "Votum – Introitus – Tangiang",
      patik: "Patik",
      dosa: "Manopoti Dosa",
      epistel: "Epistel",
      iman: "Manghatindanghon Haporseaon",
      warta: "Tingting Huria",
      jamita: "Khotbah",
      doa: "Tangiang Pelean – Pasupasu",
    },
  },
};

export enum TEMPLATE_KEY {
  SONG_XML = "song_xml",
}

export const ALKITAB_INFO: Record<ServiceMode, string[]> = {
  [ServiceMode.INDO]: [
    "Kejadian",
    "Keluaran",
    "Imamat",
    "Bilangan",
    "Ulangan",
    "Yosua",
    "Hakim-hakim",
    "Rut",
    "1 Samuel",
    "2 Samuel",
    "1 Raja-raja",
    "2 Raja-raja",
    "1 Tawarikh",
    "2 Tawarikh",
    "Ezra",
    "Nehemia",
    "Ester",
    "Ayub",
    "Mazmur",
    "Amsal",
    "Pengkhotbah",
    "Kidung Agung",
    "Yesaya",
    "Yeremia",
    "Ratapan",
    "Yehezkiel",
    "Daniel",
    "Hosea",
    "Yoel",
    "Amos",
    "Obaja",
    "Yunus",
    "Mikha",
    "Nahum",
    "Habakuk",
    "Zefanya",
    "Hagai",
    "Zakharia",
    "Maleakhi",
    "Matius",
    "Markus",
    "Lukas",
    "Yohanes",
    "Kisah Para Rasul",
    "Roma",
    "1 Korintus",
    "2 Korintus",
    "Galatia",
    "Efesus",
    "Filipi",
    "Kolose",
    "1 Tesalonika",
    "2 Tesalonika",
    "1 Timotius",
    "2 Timotius",
    "Titus",
    "Filemon",
    "Ibrani",
    "Yakobus",
    "1 Petrus",
    "2 Petrus",
    "1 Yohanes",
    "2 Yohanes",
    "3 Yohanes",
    "Yudas",
    "Wahyu",
  ],
  [ServiceMode.BATAK]: [
    "1 Musa",
    "2 Musa",
    "3 Musa",
    "4 Musa",
    "5 Musa",
    "Josua",
    "Panguhum",
    "Rut",
    "1 Samuel",
    "2 Samuel",
    "1 Raja-raja",
    "2 Raja-raja",
    "1 Kronika",
    "2 Kronika",
    "Esra",
    "Nehemia",
    "Ester",
    "Job",
    "Psalmen",
    "Poda",
    "Parjamita",
    "Angka Ende",
    "Jesaya",
    "Jeremia",
    "Andung-andung",
    "Hesekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obaja",
    "Jona",
    "Mika",
    "Nahum",
    "Habakuk",
    "Sepania",
    "Haggai",
    "Sakaria",
    "Maleaki",
    "Mateus",
    "Markus",
    "Lukas",
    "Johannes",
    "Ulaon ni Apostel",
    "Rom",
    "1 Korint",
    "2 Korint",
    "Galatia",
    "Epesus",
    "Pilippi",
    "Kolosse",
    "1 Tessalonik",
    "2 Tessalonik",
    "1 Timoteus",
    "2 Timoteus",
    "Titus",
    "Pilemon",
    "Heber",
    "Jakobus",
    "1 Petrus",
    "2 Petrus",
    "1 Johannes",
    "2 Johannes",
    "3 Johannes",
    "Judas",
    "Pangungkapon",
  ],
};
